language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7
    allow_failures:
        - php: 7
    fast_finish: true

install: composer install --dev --prefer-source
script:  phpunit
